### ISSUE TITLE
Issues with handling the `TAP_BIP32_DERIVATION` field.

### ISSUE THREAD

**Issue by cmdruid** [paulmillr/scure-btc-signer#101]
Hello I am running into issues when the `TAP_BIP32_DERIVATION` field is included within a PSBT.

I understand that this library does not support using the `TAP_BIP32_DERIVATION` field when the library is used for signing.

However, other wallets use this field for signing, and this library should not fail during signing when the field is present, it should simply ignore the field.

Another issue is that once a signature is present for a PSBT input, this library will not let you remove the `TAP_BIP32_DERIVATION` field. So you can't avoid the library failing during signing, you are simply doomed.

I feel like this can be handled better. The easiest fix would be to ignore the field, and not blow up.

**Comment by paulmillr** [comment]
Ignoring it will make the library produce different outputs for the same psbt, from other libraries.

**Comment by cmdruid** [comment]
Can you elaborate on this?

How does another library that does not sign for that input have any effect?

**Comment by paulmillr** [comment]
fixed
