### ISSUE TITLE
@scure/btc-signer not published to npm

### ISSUE THREAD

**Issue by mahnunchik** [paulmillr/scure-btc-signer#19]
It seems new package `@scure/btc-signer` was not published to NPM.

package.json has the old name: https://github.com/paulmillr/scure-btc-signer/blob/26216a976c767ec66a7d75afc1ef1881b48d3c69/package.json#L2

**Comment by paulmillr** [comment]
On purpose. We are waiting for audit report to be included.

**Comment by paulmillr** [comment]
done

**Comment by paulmillr** [comment]
cc @aulneau
