### ISSUE TITLE
P2TR: invalid leaf script=tr

### ISSUE THREAD

**Issue by mahnunchik** [paulmillr/scure-btc-signer#22]
I have faced with the following error while running examples from the readme: `Error: P2TR: invalid leaf script=tr`

https://github.com/paulmillr/scure-btc-signer/blob/26216a976c767ec66a7d75afc1ef1881b48d3c69/README.md?plain=1#L283-L293

I'm not sure:
* I'm wrong?
* There is mistake in the readme
* There is error in the source code

**Comment by mahnunchik** [comment]
One more potential mistype in the readme. According to the latest sources: https://github.com/paulmillr/scure-btc-signer/blob/26216a976c767ec66a7d75afc1ef1881b48d3c69/index.ts#L1222

There is should not be `tapMerkleRoot` key: https://github.com/paulmillr/scure-btc-signer/blob/26216a976c767ec66a7d75afc1ef1881b48d3c69/README.md?plain=1#L280

**Comment by mahnunchik** [comment]
I think the readme should be updated because there is another not existent function `tr()`:

https://github.com/paulmillr/scure-btc-signer/blob/26216a976c767ec66a7d75afc1ef1881b48d3c69/README.md?plain=1#L373

**Comment by paulmillr** [comment]
fixed: updated readme

**Comment by mahnunchik** [comment]
@paulmillr thank you for the quick fix.

P2TR-NS, P2TR-MS, and P2TR-PK should be fixed the same way to work.
