### ISSUE TITLE
Refactoring: duplicate isBytes function

### ISSUE THREAD

**Issue by mahnunchik** [paulmillr/scure-btc-signer#23]
Function `isBytes` is present in `btc-signer` module and in imported `micro-packed` module:

https://github.com/paulmillr/scure-btc-signer/blob/cf2f3d0e1fca43df94fc10cc2d3de0d68c09b5a5/index.ts#L22

https://github.com/paulmillr/micro-packed/blob/66999bf00f2054272299a9e06b68e4e861bced00/index.ts#L34

Both versions of function are used accross module:

* https://github.com/paulmillr/scure-btc-signer/blob/cf2f3d0e1fca43df94fc10cc2d3de0d68c09b5a5/index.ts#L903
* https://github.com/paulmillr/scure-btc-signer/blob/cf2f3d0e1fca43df94fc10cc2d3de0d68c09b5a5/index.ts#L924

**Comment by paulmillr** [comment]
Could you make a PR?
