### ISSUE TITLE
Transaction inputs and outputs marked as private. Why?

### ISSUE THREAD

**Issue by bordalix** [paulmillr/scure-btc-signer#30]
Any good reason for inputs and outputs on Transaction being private?

Context:

I need to inspect the inputs and outputs of a PSBT that I receive from the outside.

If on VSCode I do:

```
const tx = btc.Transaction.fromPSBT(psbt);
console.log(tx.inputs); // generates error
```

I get the error:

```
Property 'inputs' is private and only accessible within class 'Transaction'
```

I can hack it by changing to

```
const tx: any = btc.Transaction.fromPSBT(psbt);
console.log(tx.inputs); // no error
```

but the question remains: any good reason for those being private?

**Comment by paulmillr** [comment]
That's to not mess up with internal repr. Added new methods for your case, see README.
