### ISSUE TITLE
Module not found: ESM packages (@scure/btc-signer) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

### ISSUE THREAD

**Issue by GalaxySciTech** [paulmillr/scure-btc-signer#45]
Module not found: ESM packages (@scure/btc-signer) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

**Comment by paulmillr** [comment]
The module requires ESM. You are probably using common.js.
