### ISSUE TITLE
Support script type 'ms' to encode an Address

### ISSUE THREAD

**Issue by fbwoolf** [paulmillr/scure-btc-signer#55]
When calling `btc.Address.encode()` we are currently running into errors bc type `ms` throws the error, `Unknown address type=ms`. I attempt to resolve in our code in this PR: https://github.com/hirosystems/wallet/pull/4060. However, I'm not sure it is the best way to handle it and would prefer it be part of your lib if possible. It would be great if all types were supported.

**Comment by paulmillr** [comment]
yes, ms is incorrect address type, use tr.

**Comment by fbwoolf** [comment]
Ok, I'll let the app know that is reporting as a bug in our wallet. Being reported here: https://github.com/hirosystems/wallet/issues/3897

**Comment by paulmillr** [comment]
https://learnmeabitcoin.com/technical/p2ms
