### ISSUE TITLE
Merging two PSBTs finalise fails with no partialSig

### ISSUE THREAD

**Issue by radicleart** [paulmillr/scure-btc-signer#56]
Hey there,

I'm merging a tx from two PSBTs with two inputs signed independently in two Electrum wallets. 

I can see the decoded psbt contains `final_scriptwitness` for each input after signing.

However on merging and finalising I get the error `Not enough partial sign`;

```
    const txA = btc.Transaction.fromPSBT(base64.decode(quote.acceptPSBTAlice))
    const txB = btc.Transaction.fromPSBT(base64.decode(quote.acceptPSBTBob))
    const psbt = btc.PSBTCombine([txA.toPSBT(), txB.toPSBT()]);
    const txC = btc.Transaction.fromPSBT(psbt)
    txC.finalize()
```

Am i doing something wrong here? Or do I just need to update the inputs manually with the final_scriptwitness data e.g.

```updateInput(idx, final_scriptwitness) ? ```

thanks in advance!

PS I'm leaving SIGHASHTYPE as default and am setting {allowUnknowInput: true, allowUnknowOutput: true} when creating the tx.

**Comment by paulmillr** [comment]
Can you provide some information from these PSBTs? How do they look like? How many inputs are in each?

If you try to combine two different PSBTs with 1 input into PSBT with 2 inputs, it wouldn’t work:
- each input requires information from other inputs for signature (you can change this behavior by changing SIGHASHTYPE)
- input index cannot change, so you need to create two inputs tx, add outputs, then sign this tx with different wallets and then you can combine

**Comment by radicleart** [comment]
Thanks, yes this is one PBST with 2 (or three) inputs from two users. 

In scenario above Bob and Alice signed the base PBST independently, using electrum - trying to PSBTCombine failed as above. 

I've found (since posting) that I can let Bob sign first and then let Alice sign Bobs signed PSBT and [then broadcast](https://mempool.space/testnet/tx/337369e25b3d101583b418bdde71400123eb1a6825c55f2c87233e4156b29f93)
 
Before this I was going to send them to `combinepsbt` of bitcoin core rpc to see what happens - happy to do this if helpful ?

**Comment by paulmillr** [comment]
Check out new tests for this behavior https://github.com/paulmillr/scure-btc-signer/blob/38c40320953c837cc124057d1dbd247679b081ea/test/basic.test.js#L1695C23-L1695C28

if you would have any reproducible failing tests, feel free to submit them
