### ISSUE TITLE
Update `@noble/curves` and `@noble/hashes` deps

### ISSUE THREAD

**Issue by mahnunchik** [paulmillr/scure-btc-signer#57]
Please update `@noble/curves` and `@noble/hashes` dependencies to match latest version.

The same as in https://github.com/paulmillr/scure-bip32/issues/12 😉

**Comment by paulmillr** [comment]
772671d

**Comment by mahnunchik** [comment]
Build fails

**Comment by paulmillr** [comment]
see last release of scure-base

**Comment by paulmillr** [comment]
and try again, if all is good, i'll push new signer
