### ISSUE TITLE
Readme: outdated code samples

### ISSUE THREAD

**Issue by mahnunchik** [paulmillr/scure-btc-signer#58]
`Error: Wrong object type for transaction options: 2`

Old api in the documentation: https://github.com/paulmillr/scure-btc-signer/blob/47f7ab9fdaba59166bc0ac7746681923e206eef8/README.md?plain=1#L624

**Comment by mahnunchik** [comment]
Amount must be a bigint: https://github.com/paulmillr/scure-btc-signer/blob/47f7ab9fdaba59166bc0ac7746681923e206eef8/README.md?plain=1#L626-L627

**Comment by paulmillr** [comment]
Could you please update the README in PR?
