### ISSUE TITLE
make preimageWitness* methods public

### ISSUE THREAD

**Issue by huckym** [paulmillr/scure-btc-signer#61]
@paulmillr 
Is there a good reason why these methods are private? We are building an offline hardware wallet where this library is used for transaction creation, and creating the hashes that the offline hardware will sign. This library will then updateInputs and finally submit transactions. Currently we are forced to import dynamically so typescript doesn't complain that we are using a private method. Would hate to maintain a fork just for this.

**Comment by paulmillr** [comment]
reason was lack of use cases, but your case sounds solid, so we can expose it

**Comment by huckym** [comment]
Awesome! Thanks so much.
