### ISSUE TITLE
Issues with Deno

### ISSUE THREAD

**Issue by JavierCervilla** [paulmillr/scure-btc-signer#65]
Merry Christmas to all,

im trying to use this library to handle tx using deno but im getting some errors when trying to decode an unsigned hex tx:

```
import * as btc from "npm:@scure/btc-signer@1.0.0";


export const decode = (tx: any) => {
    const decoded_tx = btc.Transaction.fromRaw(tx);

    console.log(decoded_tx);

};

const txToTest = "hex_tx_here";

decode(txToTest);
```

error:

error: Uncaught (in promise) TypeError: this.data.subarray is not a function
    at Reader.bytes

**Comment by JavierCervilla** [comment]
thank you so much

**Comment by JavierCervilla** [comment]
i tested it too on v 1.1.1 and same error

**Comment by paulmillr** [comment]
Pass uint8array, not hex.

**Comment by JavierCervilla** [comment]
okey ser thanks for your quick response, i passed this error but now getting other one error: Uncaught (in promise) Error: Reader(): 1552 bytes 0 bits left after unpack: 00010006000000000200020....

**Comment by JavierCervilla** [comment]
also i readed this in the npm docs page: ```We support both PSBTv0 and draft PSBTv2 (there is no PSBTv1). If PSBTv2 transaction is encoded into PSBTv1, all PSBTv2 fields will be stripped.

We strip 'unknown' keys inside PSBT, they needed for new version/features support, however any unsupported feature/new version can significantly break assumptions about code. If you have use-case where they are needed, create a github issue.

PSBTv2 features tx_modifiable and taproot+bip32 are not supported yet.

``` the tx im using is a counterparty tx

**Comment by JavierCervilla** [comment]
i see that error seems to be with the tx itself
error: Uncaught (in promise) Error: checkScript: non-wrapped ms

**Comment by JavierCervilla** [comment]
i see that error seems to be with the tx itself
error: Uncaught (in promise) Error: checkScript: non-wrapped ms

**Comment by paulmillr** [comment]
We don't officially support counterparty, so you will need to debug it by yourself.

**Comment by JavierCervilla** [comment]
looks like problem is with multisig tx not just counterparty but okey i will try to dig on it, thanks for your help
