### ISSUE TITLE
How to use this in tandem with bip39?

### ISSUE THREAD

**Issue by afeezaziz** [paulmillr/scure-btc-signer#68]
Referring to [scure-bip39](https://github.com/paulmillr/scure-bip39), how can I generate mnemonic using bip39 and then use btc signer to get private key, public key and then eventually addresses?

**Comment by paulmillr** [comment]
I think you need bip32 for that. Bip39 generates a bunch of bytes (master key) and then you can use it in bip32.

**Comment by paulmillr** [comment]
yes

**Comment by afeezaziz** [comment]
Thank you @paulmillr
