### ISSUE TITLE
Regression 1.2.2 `getInputType` not exported

### ISSUE THREAD

**Issue by mahnunchik** [paulmillr/scure-btc-signer#84]
In version 1.2.2 `getInputType` method was moved out of tx. This change broke compatibility with our implementation of Bitcoin Cash support. https://github.com/CoinSpace/cs-bitcoin-wallet/commit/a509a0b30d58264bbdaf73c69991ba4adca6f7f6

Could you please export `getInputType` method?

**Comment by paulmillr** [comment]
Fixed in 1.3.0
