### ISSUE TITLE
Custom Script Tapscript not working?

### ISSUE THREAD

**Issue by kevinfaveri** [paulmillr/scure-btc-signer#86]
That's probably my fault;
Overall the library is way more straightforward and battery packed than other fragmented libraries, but I'm struggling to make a simple tapscript work (which seems pretty straightforward with bitcoinjs or cmd/tapscript, at the cost of fragmentation)...

I'm creating a tapscript  with a custom script that will pay for another transaction on a meta protocol:
```
 const { publicKey } = getP2TRWallet()
  const taprootInternalKey = ecdsaPublicKeyToSchnorr(publicKey)
  const outputScript = btc.Script.encode([
    taprootInternalKey,
    btc.OP.CHECKSIG,
    btc.OP.OP_0,
    btc.OP.IF,
   randomId,
    btc.OP.ENDIF
  ])

  const taprootPayment = btc.p2tr(
    taprootInternalKey,
    [
      {
        script: outputScript,
        leafVersion: 192,
      }
    ],
    network,
    true
  )
  return taprootPayment
  ```
  
  and then, I pay to taprootPayment.address. Of course. This work flawlessly, the problem only really happens when I create the transaction to spend from this tapscript, in which the input is:
  ```
  tx.addInput({
    txid: hex.decode(utxo.txid),
    index: utxo.vout,
    witnessUtxo: {
      script: tapscriptCommitment.script,
      amount: BigInt(utxo.value)
    },
    ...tapscriptCommitment,
    sighashType: btc.SigHash.ALL,
    sequence: 0xfffffffd
  })
  ```
  
  And then I proceed to build the outputs etc, sign the transaction, and submit to the blockchain. ALL GOOD.

Except that the tapscript does not get embedded on the hex of the transaction, check here: https://mempool.space/testnet/tx/f8d7bf9143bb8f41f0934ee35791ae75ebe6ffa4bb23de3287b635ecd8d9eb8f (clicking on details, you can see that there's no P2TR tapscript)

My best bet, is that I'm creating the custom script wrong in some manner. Still getting used to the library to consolidate on my own projects. 

Would appreciate any help you can provide @paulmillr 🙏

**Comment by victorkirov** [comment]
To ensure you're signing the script path instead of the key path, I'd set up these to different pub keys:
```
const outputScript = btc.Script.encode([
    taprootInternalKey, // <<<< THIS
    btc.OP.CHECKSIG,
    btc.OP.OP_0,
    btc.OP.IF,
   randomId,
    btc.OP.ENDIF
  ])

  const taprootPayment = btc.p2tr(
    taprootInternalKey, // <<<< AND THIS
    [
      {
        script: outputScript,
        leafVersion: 192,
      }
    ],
    network,
    true
  )
```

Then sign with the key in the script.

**Comment by victorkirov** [comment]
It would actually be pretty cool if there was a param that could be passed in to prefer signing the script over the PK path in this scenario.

**Comment by kevinfaveri** [comment]
Hmm thanks @victorkirov. So, I'm using my Taproot seed, and generating the internal key for it.
But I also did this:
```
export const tapscriptPrivateKey = secp.utils.randomPrivateKey()
export const internalPublicKey = secp.getPublicKey(tapscriptPrivateKey);
export const tapscriptPublicKey = ecdsaPublicKeyToSchnorr(internalPublicKey)
```

So I different than my taproot seed phrase wallet.
Or u meant, something like this:
```
const outputScript = btc.Script.encode([
    taprootInternalKey1, (the one that can unlock)
    btc.OP.CHECKSIG,
    btc.OP.OP_0,
    btc.OP.IF,
   randomId,
    btc.OP.ENDIF
  ])

  const taprootPayment = btc.p2tr(
    taprootInternalKey2, (the one that was generated random)
    [
      {
        script: outputScript,
        leafVersion: 192,
      }
    ],
    network,
    true
  )
  ```
  
  ---
  
  And agree on path spending forcing.

**Comment by kevinfaveri** [comment]
I'm lowkey thinking about adding some PRs to add support for this kinda of thing. I get @paulmillr goal is to make this lib easier to use and more idiomatic, but when you have to go out a bit with custom scripts, it kinda has to go through lots of rounds of workarounds that should just be abstracted for better DX.

**Comment by paulmillr** [comment]
ordinals api is coming soon

**Comment by kevinfaveri** [comment]
> ordinals api is coming soon

Nice. This is good, but can we enable custom scripting path spending in some way in current lib?

What are my options if I want to make it work right now, do u have any suggestion to my custom script input above? I should just not possible to make this tapscript works?

**Comment by kevinfaveri** [comment]
Got it, i might have to move away from scure for custom scripting txns for now then as I want something ready before halving.

Or do u have a dev branch I could fork and start using?

**Comment by paulmillr** [comment]
the branch would be ready later this week: there would still be time before halving.

**Comment by kevinfaveri** [comment]
perfect sir. thank you, anxious waiting for this!

**Comment by paulmillr** [comment]
https://github.com/paulmillr/scure-btc-signer/tree/ord

**Comment by paulmillr** [comment]
for example, see `Example (fake)` in ordinals.test.js. Docs would be coming after the feature is more stable. Custom scripts are there.

**Comment by kevinfaveri** [comment]
Nice, ur a chad sir. Thank you, I will study this branch tomorrow
Doing Gods work

**Comment by ZionNFT** [comment]
> for example, see `Example (fake)` in ordinals.test.js. Docs would be coming after the feature is more stable. Custom scripts are there.

thank you Paul! keen to get ordinals/runes stuff through

**Comment by paulmillr** [comment]
Any feedback on the branch folks? Have you managed to write working code?

**Comment by kevinfaveri** [comment]
Hi! Crunching atm so didnt had time to integrate it yet; once I do, will circle back

**Comment by bitspill** [comment]
1.3.0 looks very promising I had almost successfully integrated the ord branch when this released, tonight I'll pivot to the public release again and continue. 

Can we get customScript support in the utxo selector here as well?
https://github.com/paulmillr/scure-btc-signer/blob/1.3.0/src/utxo.ts#L153

**Comment by paulmillr** [comment]
@kevinfaveri usage from first post: https://gist.github.com/paulmillr/e6f4ee87715e8c5510ce39326fad7129
