### ISSUE TITLE
Deduct fee from outputs or add option to send max

### ISSUE THREAD

**Issue by gregdhill** [paulmillr/scure-btc-signer#91]
I want to have something like `subtractfeefromamount` in `selectUTXO` in the case I want to send the exact amount in the UTXOs currently it silently fails and returns `undefined`. Perhaps there is another way to build this but since I have to define the outputs ahead of time I cannot estimate the fees beforehand to subtract there.

**Comment by paulmillr** [comment]
> I want to have something like subtractfeefromamount in selectUTXO in the case I want to send the exact amount in the UTXOs currently it silently fails and returns undefined. Perhaps there is another way to build this but since I have to define the outputs ahead of time I cannot estimate the fees beforehand to subtract there.

This should work for sending all value from UTXOs:

```ts
const s = btc.selectUTXO(utxo, [], 'all', {
  changeAddress: toAddress, // everything goes to change address (except fee and dust UTXO)
  feePerByte: FEE,
});
```

**Comment by gregdhill** [comment]
Hey @paulmillr thanks for the reply, but just to confirm: if I provide more inputs to `selectUTXO` than necessary will this act similarly to the "default" selection strategy and only those inputs required to satisfy exactly the fee? Also if I still want to emulate the default strategy and select the biggest UTXOs first, is it enough to sort the inputs before I provide them to that function?
