### ISSUE TITLE
Support for having *required* UTXOs that must be used on UTXO Selection algo

### ISSUE THREAD

**Issue by kevinfaveri** [paulmillr/scure-btc-signer#93]
UTXO selection works well for the most part, but what if I want to use a specific spent transaction to trigger an RBF?

Two scenarios I see this could be needed (both when doing RBF):
- Just adjust the change if not utxos needed anymore other than the required (which are the spent UTXOs from the transaction to be replaces)
- Preserve the required (spent utxos) in the order they are provided but add more if needed to pay for a new fee rate or changes in outputs (by preserving the spent in the provides order as inputs, we can have an rbf that adds extra utxo to pay to fully cover)

Implementation wise, I think both scenarios are the same thing... But let me know what you think and if this can be arranged @paulmillr 

Appreciate

**Comment by paulmillr** [comment]
It's unclear how the API would look like.

**Comment by kevinfaveri** [comment]
I think we would have two options, simple one / dumb:
- Receive a "nonOptionalUtxos" or something like this param on the utxo selection logic, and make
it be the first input always. Then, check if simple change on change output would deal with the payment that is needed for all outputs and fee rate; if not, then also add extra inputs using the logic of utxo selection you did
OR
- RBF transaction option: read hex of it, get transaction object and allow to provide a list of non spent utxos as addition for covering for fees of a new fee rate asked for IF changing the change output is not enough

**Comment by paulmillr** [comment]
So the main case is providing a good API for RBF?

**Comment by kevinfaveri** [comment]
Yes! That allows for topping up with more inputs if needed (if existing spent inputs change of change output wouldnt make it enough to improve the fee rate)

**Comment by kevinfaveri** [comment]
There's multiple cases for RBF on mempool right now:
1 - You want to keep your transaction within next block, and keep bumping it to get it in
or 
2 - You want to snipe a transaction that is SIG_SINGLE | ANYONECANPAY (Ordinals/Runes marketplaces suffer from such problem atm) and the majority of miners is not respecting nSequence informing RBF is disabled, so a big problem. A way to counter this is by doing the same the mempool snipers are doing: grab your transaction hex from mempool, and update it paying more fees and resubmit (so, sniping against sniping to guarantee you get what you are trying to buy)

**Comment by kevinfaveri** [comment]
If we have an API for RBFing a transaction, then I could use the UTXO selection features for first fire; and the RBF API for subsequent fires

**Comment by kevinfaveri** [comment]
I originally requested as addition to UTXO selection in case there would be no willingness to support a first class RBF feature, which is could be extra work than just making the ability to put "fixed utxos/inputs" on a transaction; and cuz it feels like the RBF API will have to borrow same utxo selection rules

**Comment by paulmillr** [comment]
I have heard that nodes/miners started disabling RBF. Have you heard anything about that?

**Comment by kevinfaveri** [comment]
> I have heard that nodes/miners started disabling RBF. Have you heard anything about that?

yes haha
its true
from what u see on mempool 80% now disable, which means u can rbf almost anything since respecting the rbf sequence is policy

**Comment by paulmillr** [comment]
> UTXO selection works well for the most part, but what if I want to use a specific spent transaction to trigger an RBF?
> Two scenarios I see this could be needed (both when doing RBF):
> Just adjust the change if not utxos needed anymore other than the required (which are the spent UTXOs from the transaction to be replaces)
> Preserve the required (spent utxos) in the order they are provided but add more if needed to pay for a new fee rate or changes in outputs (by > preserving the spent in the provides order as inputs, we can have an rbf that adds extra utxo to pay to fully cover)

Seems reasonable even outside of RBF (reveal some tapscript output which doesn't have enough money for fees). Added in e146034
