### ISSUE TITLE
What is a simple way to getAddress of an output?

### ISSUE THREAD

**Issue by kevinfaveri** [paulmillr/scure-btc-signer#94]
I have a simple code:
```
const txnOutputs: ReturnType<typeof tx.getOutput>[] = []
      for (let i = 0; i < tx.outputsLength; i++) {
        txnOutputs.push(tx.getOutput(i))
      }
      ```

How would I go about getting the address (if this output was a `addOutputAddress`)?
Of course, for logging the script, I can easily do by getting `bytesToHex(txnOutputs[0].script)`. But is there an elegant shortcut to get an address, if it exists?

**Comment by kevinfaveri** [comment]
I suppose this is as elegant as it gets for getting the destination address, right?
```
   const outScript = vout.script ? btc.OutScript.decode(vout.script) : undefined
   const address = outScript? btc.Address(getScureNetworkFromEnv(this._network)).encode(outScript) : undefined
```

I think this can be seen as a suggestion, but similarly to how we have `addOutputAddress` which is a shortcut, would be nice to have the `txn.getOutput` return the `address` field as well which can be undefined if script only.

**Comment by paulmillr** [comment]
Now there is a method to get address back:

```ts
for (const [address, amount] of TX_TEST_OUTPUTS) {
  const idx = tx.addOutputAddress(address, amount);
  deepStrictEqual(tx.getOutputAddress(idx), address);
}
```
