### ISSUE TITLE
btc.Transaction.fromPSBT() fails in react-native@0.74.2

### ISSUE THREAD

**Issue by ph101pp** [paulmillr/scure-btc-signer#97]
Hello!

Thank you for your work on the scure libraries, they work great!

That said, I'm having trouble getting `btc.Transaction.fromPSBT` working in `react-native@0.74.2`

Other things work great: Creating `btc.selectUTXO`, `tx.toPSBT`, just `btc.Transaction.fromPSBT` fails with: 
```
Reader(magic): TypeError: Cannot read property 'prototype' of undefined
```
Thrown somewhere in `decodeStream`.

We have polyfills for `crypto`, `TextEncode`/`TextDecode`, `Buffer`, `stream` etc.

This same code works in a web environment with the same inputs.

Any input/help would be appreciated!

This might be an issue for [micro-packed](https://github.com/paulmillr/micro-packed) instead. 
Let me know and I can open an issue there.

**Comment by paulmillr** [comment]
Spent a lot of time on this but it works correctly in react native 0.74.2.

You will need to create a reproducible repo with exact code which is breaking.

**Comment by paulmillr** [comment]
We don't support `Buffer`s. You must always use Uint8Array. Something somewhere would break, because buffer is shit. For example, it completely redefines semantics of slice to make it like subarray instead of copy.

**Comment by ph101pp** [comment]
I wasn't aware of that re: Buffers! Thanks!

Turns out that `fastestsmallesttextencoderdecoder` TextDecoder shim isn't up to full spec / only supports `utf-8` for speed purposes ( I'm assuming that is the issue). Replacing the shim fixed the issue.

Other shims that make similar compromises suggest to use `Buffer` for other types of conversions, but after your comment above I'm assuming using TextDecoder was a deliberate choice. 

Thanks again for your time and sorry for the churn, I was banging my head against the table.
